add example with dynamic group of progress bars
willmcgugan/rich pull request #1504
Opened 2021-09-19 07:53 UTC by boegel

## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [x] Other: examples

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
   - Is this required for examples too? If so, happy to look into it...
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Additional example for progress bars, more dynamic in nature than the existing [live_progress.py](https://github.com/willmcgugan/rich/blob/master/examples/live_progress.py>); see also discussion in #1500 .

Screenshot while running:

![image](https://user-images.githubusercontent.com/620876/133919699-76d80e9e-8bc8-4cee-bc32-ea27aad50797.png)

Screenshot when done:

![image](https://user-images.githubusercontent.com/620876/133919701-dd850902-5d01-4c20-ac8c-d9236a41ee6f.png)

2021-09-22 20:30 UTC, willmcgugan requested changes
Looks good! Couple of small requests.

Could you run this against the latest black?

2021-09-22 20:30 UTC, willmcgugan commented on examples/dynamic_progress.py
> +from rich.console import RenderGroup
RenderGroup was deprecate, the new name is just `Group`

2021-09-22 20:30 UTC, willmcgugan commented on examples/dynamic_progress.py
> +group = RenderGroup(
Should be `Group` here. Could you also give `group` a more descriptive name?

2021-09-22 20:35 UTC, willmcgugan commented
Nice work!

Could you maybe put the app progress in a Panel to separate it visually? And speed it up a fraction...

2021-11-20 09:11 UTC, boegel commented
@willmcgugan Anything in particular that's blocking this PR? Happy to make additional changes if needed.

2021-11-20 10:51 UTC, willmcgugan approved these changes

2021-11-20 10:51 UTC, merged

2021-11-20 10:56 UTC, willmcgugan commented
Sorry, forgot about this one. Looks good. Thanks!