Proofread Swiss German readme
willmcgugan/rich pull request #1680
Opened 2021-11-11 21:36 UTC by The-Compiler

## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Less typos, yay! There's no official written version of Swiss German, and this version reads horrible to me to be honest (but I know the author, so I can say so :laughing:), but I only fixed the obvious typos.

2021-11-13 12:03 UTC, das-g requested changes
These changes improve the translation and its correctness significantly.

Only some minor nitpicks:

2021-11-15 15:48 UTC, willmcgugan commented
Let me know when this is ready to merge. I'm afraid I can't contribute!

2021-11-16 12:46 UTC, Chive commented on README.de-ch.md
> +Installation mit `pip` oder mit dim liäblings PyPI Päckli-Mangager.
```suggestion
Installation mit `pip` oder mit dim liäblings PyPI Päckli-Manager.
```

2021-11-17 17:01 UTC, ubaumann commented
No rules in Swiss German so everything is fine and many typos are found (sorry for that).
All changes are fine for me

2021-11-18 13:15 UTC, The-Compiler commented
@willmcgugan Should be ready now from my POV!

2021-11-18 13:16 UTC, merged

2021-11-18 13:16 UTC, willmcgugan commented
Fantastisch! Thanks all.