Add flag to render in binary/decimal suffix in DownloadColumn
willmcgugan/rich pull request #380
Opened 2020-10-13 01:29 UTC by amartya-dev

Add a test for rendering binary suffix in test_progress.py

## Type of changes

- [ ] Bug fix
- [x] New feature
- [ ] Documentation / docstrings
- [x] Tests
- [ ] Other

## Checklist

- [x] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.
An additional feature in #323

2020-10-14 13:35 UTC, amartya-dev commented
@willmcgugan I have added the discussed feature, let me know in case anything else is required

2020-10-14 14:00 UTC, willmcgugan requested changes
Rather than "decimal_suffix", let's call it "binary_units" which should default to False.

2020-10-14 14:09 UTC, amartya-dev commented on rich/progress.py
> +        self.decimal_ssuffix = decimal_suffix
Alright!!

2020-10-14 20:44 UTC, Edward-Knight approved these changes

2020-10-16 13:44 UTC, merged

2020-10-16 13:44 UTC, willmcgugan commented
LGTM. Thanks.