Changes typing for logging level to accept both str and int
willmcgugan/rich pull request #461
Opened 2020-12-02 16:00 UTC by heavelock

## Type of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation / docstrings
- [ ] Tests
- [x] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/psf/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x ] I accept that @willmcgugan may be pedantic in the code review.

## Description

The standard logging module accepts either str or int as a logging level. str is internally casted to int. Rich does not do anything with the logging level so there is no reason to limit the type here.

2020-12-02 22:50 UTC, willmcgugan requested changes

2020-12-02 22:50 UTC, willmcgugan commented on rich/logging.py
> +        level: Union[int, str] = logging.NOTSET,
Can you update the docstring above please.

2020-12-03 10:34 UTC, heavelock commented
Black complains in CI at file I did not touch and when I am trying to run it on my system it does not complain.

2020-12-03 10:35 UTC, willmcgugan commented
That's my fault. I'll fix that. Thanks for the PR.

2020-12-03 10:35 UTC, merged